/**
 * Dynamic runtime environment helper.
 *
 * In production (Docker), values come from window.env (generated by docker-entrypoint.sh).
 * This dynamically checks window.env on every access so it never gets stuck with a stale value.
 */
export const getApiUrl = () => {
  // 1. Check window.env (runtime Docker container env)
  if (typeof window !== "undefined" && window.env && window.env.REACT_APP_API_URL) {
    return window.env.REACT_APP_API_URL;
  }

  // 2. Check process.env (local React development)
  if (process.env.REACT_APP_API_URL) {
    return process.env.REACT_APP_API_URL;
  }

  // 3. Fallback:
  // If in browser (production), use relative "/api" (matches nginx proxy pass)
  // If in Node/SSR, fallback to localhost
  if (typeof window !== "undefined" && window.location && window.location.origin) {
    return "/api";
  }

  return "http://localhost:8000";
};

const env = {
  get REACT_APP_API_URL() {
    return getApiUrl();
  },
};

export default env;
